export const TRAIN_STATIONS = [
  {
    id: 1,
    name: 'Station 1',
    address: '123 Something St',
    city: 'Baton Rouge',
    state: 'LA',
    zip: '11111',
    managerId: undefined,
  },
  {
    id: 2,
    name: 'Station 2',
    address: '123 Something St',
    city: 'Mobile',
    state: 'AL',
    zip: '11111',
    managerId: undefined,
  },
  {
    id: 3,
    name: 'Station 3',
    address: '123 Something St',
    city: 'Dallas',
    state: 'TX',
    zip: '11111',
    managerId: undefined,
  },
  {
    id: 4,
    name: 'Station 4',
    address: '123 Something St',
    city: 'Jackson',
    state: 'MS',
    zip: '11111',
    managerId: undefined,
  },
];
